import React from 'react'

export const TaskDetails = (props : {}) => {
  return (
    <div>
       <div className={` h-[30vh] bg-[url(https://files.catbox.moe/fuijnn.png)]`}>
      </div>
      <div className='pb-3 text-3xl tracking-wide	 font-bold text-pink-600'>
        Title 
      </div>
      <div className='pb-3 tracking-wide	'>
        DESC.....................sdasd............... sad............. sd .........
        DESC.....................sdasd............... sad............. sd .........
        DESC.....................sdasd............... sad............. sd .........
        DESC.....................sdasd............... sad............. sd .........
        DESC.....................sdasd............... sad............. sd .........
        DESC.....................sdasd............... sad............. sd .........
        DESC.....................sdasd............... sad............. sd .........
        DESC.....................sdasd............... sad............. sd .........
        DESC.....................sdasd............... sad............. sd .........
        DESC.....................sdasd............... sad............. sd .........
        DESC.....................sdasd............... sad............. sd .........
        DESC.....................sdasd............... sad............. sd .........
        DESC.....................sdasd............... sad............. sd .........
      </div>
      <div className='bg-pink-400 w-fit rounded-xl tracking-wide	 font-extrabold text-white px-2  '><span>date time </span> </div>
       
    </div>
  )
}
